# PLEASE DO NOT MODIFY THIS FILE. IT IS AUTOGENERATED AND WILL BE OVERWRITTEN. Please don't build this Dockerfile yourself either. Use Armbian ./compile.sh instead.
FROM ghcr.io/armbian/docker-armbian-build:armbian-ubuntu-noble-latest
# PLEASE DO NOT MODIFY THIS FILE. IT IS AUTOGENERATED AND WILL BE OVERWRITTEN. Please don't build this Dockerfile yourself either. Use Armbian ./compile.sh instead.
RUN echo "--> CACHE MISS IN DOCKERFILE: apt packages." && \
 DEBIAN_FRONTEND=noninteractive apt-get -y update && \
 DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends bash git psmisc uuid-runtime bc binfmt-support bison bsdextrautils libc6-dev make dpkg-dev gcc ca-certificates ccache cpio device-tree-compiler dialog dirmngr dosfstools dwarves e2fsprogs flex gawk gettext gnupg gpg imagemagick jq kmod libbison-dev libelf-dev libfdt-dev libfile-fcntllock-perl libmpc-dev libfl-dev lz4 libncurses-dev libssl-dev libusb-1.0-0-dev linux-base locales lsof ncurses-base ncurses-term ntpsec-ntpdate patchutils pkg-config pv qemu-user-static arch-test rsync swig u-boot-tools udev uuid-dev zlib1g-dev file tree expect colorized-logs unzip zip pigz xz-utils pbzip2 lzop zstd parted gdisk fdisk aria2 curl axel wget parallel rdfind binwalk python3 libpython3-dev libffi-dev libgnutls28-dev gcc-x86-64-linux-gnu gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi gcc-arm-linux-gnueabihf gcc-riscv64-linux-gnu libc6-dev-riscv64-cross libc6-amd64-cross mkbootimg g++-aarch64-linux-gnu g++ btrfs-progs cryptsetup openssh-client f2fs-tools nilfs-tools libclang-dev xfsprogs gcc-arm-linux-gnueabi zerofree lvm2 rustc cargo build-essential qemu-utils qemu-utils libudev-dev libusb-1.0-0-dev dh-autoreconf build-essential gcc-arm-linux-gnueabi gcc-or1k-elf qemu-utils qemu-utils
# Use C.UTF-8 locale which is available in rootfs from the very first command
WORKDIR /armbian
ENV ARMBIAN_RUNNING_IN_CONTAINER=yes LANG=C.UTF-8
ADD . /armbian/
# RUN echo "--> CACHE MISS IN DOCKERFILE: running Armbian requirements initialization." && \
#  ARMBIAN_INSIDE_DOCKERFILE_BUILD="yes" /bin/bash "/armbian/compile.sh" requirements SHOW_LOG=yes && \
#  rm -rf "/armbian/output" "/armbian/.tmp" "/armbian/cache"

